INSERT INTO PARTICIPANT (ID, LEVEL, NAME) VALUES (1, 'BEGINNER', 'Martin Wieler');
INSERT INTO PARTICIPANT (ID, LEVEL, NAME) VALUES (2, 'PRO', 'Norman Kern');
INSERT INTO PARTICIPANT (ID, LEVEL, NAME) VALUES (3, 'GURU', 'Adam Bien');
INSERT INTO PARTICIPANT (ID, LEVEL, NAME) VALUES (4, 'BEGINNER', 'Sabine Taschke');
INSERT INTO PARTICIPANT (ID, LEVEL, NAME) VALUES (5, 'ADVANCED', 'Frank Dröge');
